trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Use Java 21
- task: JavaToolInstaller@0
  displayName: 'Set Java 21'
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Check Java version
- script: java -version
  displayName: 'Check Java Version'

# Build Maven Project
- task: Maven@4
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
